gratipay/inside.gratipay.com

.travis.yml, Makefile
http://docs.travis-ci.com/user/workers/container-based-infrastructure/
=> Use container-based architecture for Travis

www/howto/manage-risk.spt
This makes a place for https://github.com/gratipay/inside.gratipay.com/issues/119 to land.
=> start a risk management program

www/howto/manage-risk.spt
=> unroll some abbreviations

www/howto/manage-risk.spt
In light of the weekend's activity on #119, etc.
=> Rewrite AML section

www/howto/manage-risk.spt
Too verbose otherwise, we link out to full discussion.
=> Use an abbrevation for FFIEC

www/howto/manage-risk.spt
=> Remove errant article

www/howto/manage-risk.spt
=> Distance ourselves from crime and harm

Makefile, requirements.txt
The enables to install wheels on Windows
=> Do not use hardcoded filenames for requirements.txt

www/appendices/channels.spt, www/howto/manage-queues.spt, www/howto/sweep-the-radar.spt
=> document the Radar

www/howto/review-teams.spt
=> revise Review Teams

www/appendices/see-also/index.spt
To be landed with https://github.com/liberapay/liberapay.com/issues/1.
=> note Liberapay

www/appendices/see-also/index.spt
Reverts gratipay/inside.gratipay.com#478
=> Revert "note Liberapay"

www/appendices/security-program.md
Making some changes with @TheHmadQureshi in https://github.com/gratipay/inside.gratipay.com/issues/369, and realizing we really want to have this text version-controlled. This should be a good enough place for it for now.
=> start versioning security program text from H1

www/appendices/see-also/index.spt
@techtonik merged #478 too soon, because Liberapay hasn't actually launched yet. Once @Changaco lands https://github.com/liberapay/liberapay.com/issues/1, *then* we can merge this PR. ;-)
=> Re-note Liberapay

www/howto/seek-consent.spt, www/howto/support-users.spt
Closes https://github.com/gratipay/inside.gratipay.com/issues/411 and contributes to https://github.com/gratipay/inside.gratipay.com/issues/319.
=> write a doc on seeking consent

www/appendices/security-program.md
Prevents haggling.
https://github.com/gratipay/inside.gratipay.com/issues/514#issuecomment-187891557
=> pin bounties to set amounts

www/appendices/security-program.md
Hopefully this helps address some of the concerns surfacing at https://github.com/gratipay/inside.gratipay.com/issues/538#issuecomment-198345438.
=> explain small bounties

www/appendices/disclosures.spt, www/appendices/index.spt
Closes #512 and supports #560.
=> start a page listing our security disclosures

www/big-picture/fr_FR/index.spt, www/big-picture/fr_FR/welcome.spt
=> i18n for Big Picture

www/howto/patch-manage.spt
=> Start a HOWTO about patch management

www/howto/manage-patches.spt
https://github.com/gratipay/inside.gratipay.com/pull/719#discussion_r70798523
=> Rename to "Manage Patches"

www/howto/develop-software.spt
Just picked some @whit537's sentences from gratipay/gratipay.com#4094 and added it to the related how-to.
=> Talk about docs in the "Develop Software" how-to

www/howto/run-payday.spt
https://github.com/gratipay/inside.gratipay.com/issues/745#issuecomment-235930688
=> Incorporate baton handing into our payday process

.travis.yml
Look okay, @kaguillera @rohitpaulk @aandis @JessaWitzel et al.?
=> Update heroku api key

www/big-picture/welcome.spt
The OCI is dead. Long live the OCI!
More context: https://github.com/gratipay/inside.gratipay.com/issues/757#issuecomment-256234457.
=> Open Company → Open Organization

www/big-picture/index.spt, www/big-picture/org-chart.spt, www/big-picture/roadmap.spt
=> Bring over content that was loading up the radar

www/howto/take-money.spt
I find myself repeating this info over and over, and now I want to say it to a bunch of translators (#189).
=> Start a howto for taking money

www/big-picture/fr_FR/welcome.spt
It's starting to look nicer :-) 
The only thing I need to review with somebody is the usage of "owner". I was not able to find French word for it, since the translation of "owner" is more like "I own the project", which is too far away from the _real_ meaning. I've read your discussion about the fact you don't want to use words like "collaborator" or "contributor" for this role, so I choose to translate "owner" by "acteur" (~ "A participant in an action or process").
=> Improve french translation of the welcome page

www/appendices/channels.spt, www/appendices/chat.spt, www/appendices/index.spt
We decided to bring back Slack (#913).
=> Bring back chat

www/howto/run-payday.spt
Per https://github.com/gratipay/inside.gratipay.com/issues/536.
=> Stop migrating tips

www/appendices/security-program.md
I have added a couple of rules to ensure quality reports.
=> Update HackerOne policy

www/big-picture/roadmap.spt
See https://github.com/gratipay/gratipay.com/issues/3399#issuecomment-270397927. 💃 🌻 
---------------------------
=> The pivot is done!

www/howto/use-github.spt
Content lifted from https://github.com/gratipay/inside.gratipay.com/issues/878#issuecomment-270364244.
=> Start a page to collect GitHub notes

www/howto/translate-gratipay.spt
Spell a word right, standardize a heading.
=> Tinker w/ Translate Gratipay

www/big-picture/brand.spt, www/big-picture/index.spt, www/big-picture/values.spt
This is my proposal to ~~close~~ *move towards* https://github.com/gratipay/inside.gratipay.com/issues/72, by adopting the internationally recognized cooperative values and principles, which [date back to 1844](https://en.wikipedia.org/wiki/Rochdale_Principles). Additionally, this PR solidifies our identity as an *open* cooperative by adopting the values articulated in the recently published [Open Organization Definition](https://opensource.com/open-organization/resources/open-org-definition).
(With these burgeoning values it seemed time to give them their own page on the site; it was always a bit idiosyncratic to have them under "Brand," anyway).
My proposal is that we identify as a _worker_ cooperative, and that adoption of this proposal be by consensus of the nine current members of …
=> Identify as a cooperative

www/howto/run-masspay.spt
https://github.com/gratipay/inside.gratipay.com/issues/1028#issuecomment-290389859
=> Adapt to new MassPay UI

www/appendices/security-program.md
Here's a bit of blowback from H1. I'll leave the merge for you, @EdOverflow. :-)
=> Adapt to HackerOne Markdown implementation

www/big-picture/roadmap.spt
We landed beancount! Now to finish setting up the books ...
=> Update Accounting Roadmap

www/howto/run-payday.spt
First hit on https://github.com/gratipay/inside.gratipay.com/issues/1024#issuecomment-288832853, @clone1018 at https://github.com/gratipay/inside.gratipay.com/issues/1055#issuecomment-299278996. Not sure if @rohitpaulk dodged or fixed in between.
=> Note need to symlink /app during payday

certs/gratipay.com.ini, www/howto/install-a-tls-certificate.spt
https://github.com/gratipay/inside.gratipay.com/issues/1051
=> Update TLS cert docs

www/appendices/see-also/index.spt
Closes https://github.com/gratipay/inside.gratipay.com/issues/1064.
=> Note FundRequest

www/appendices/see-also/index.spt
Not sure why this didn't break production, but it breaks my local.
=> Fix bug on see also, and prevent in future

www/appendices/chat.spt
=> Drop back to shared invite for now

www/appendices/see-also/index.spt
Via https://www.reddit.com/r/opensource/comments/6d17na/question_would_you_be_willing_to_commit_1_of_your/dhzc9gm/.
=> Note Let's Open Source

www/howto/download-statements.spt
=> Update PayPal download instructions

www/howto/keep-secrets.spt, www/howto/manage-risk.spt
Per https://github.com/gratipay/inside.gratipay.com/issues/175.
=> Replace LastPass reference with 1Password.

www/appendices/see-also/index.spt
Per email received from them, can't find web version.
=> Mark Generous as discontinued

www/howto/download-statements.spt
Why click and then click back?
=> Tweak PNC download instructions

www/howto/handle-security-issues.spt
We've made some tweaks to our program recently. cc: @edoverflow
=> Trim up security howto

www/appendices/chat.spt
http://inside.gratipay.com/howto/refresh-the-slack-invite-link
=> Update Slack invite link

www/appendices/incoming.spt
Community page to keep up with https://github.com/gratipay/inside.gratipay.com/issues/1114.
Anyone is welcome to contribute!
Every time it was asked: https://github.com/gratipay/project-review/issues?utf8=%E2%9C%93&q=is%3Aissue%20%22How%20did%20you%20hear%20about%20Gratipay%3F%22
=> Track "how did you hear about Gratipay?" responses

Dockerfile
Created a Dockerfile which can be used to run inside.gratipay.com in a Docker container which should make the development process easier.
=> Dockerize inside.gratipay.com
